title: "Lavish Salon & Spa | 1 John 3:1"
email: alex@macarthur.me
description:
baseurl: "http://www.lavishsalonspamn.com/"
url: ""
exclude: [node_modules, gulpfile.js, Gemfile, Gemfile.lock, package.json, assets/scss, assets/js]
markdown: kramdown

name: "Lavish Salon and Spa"
phone: 507-925-4247
facebook: https://www.facebook.com/Lavish.salon.spa.1
address: "266 2nd Avenue West"
description: "We're a full-service salon and spa in Echo, MN offering a wide variety of hair, skin, & nail services."
