title: "Lavish Salon & Spa | 1 John 3:1"
email: alex@macarthur.me
description: 
baseurl: ""
url: ""
exclude: [node_modules, gulpfile.js, Gemfile, Gemfile.lock, package.json]
markdown: kramdown

name: "Lavish Salon and Spa"
phone: 507-925-4247
facebook: https://www.facebook.com/Lavish.salon.spa.1
address: "266 2nd Avenue West"
description: "Lavish Salon and Spa provides quality hair, nail, and skin services, as well as premium beauty products."
